package constants

var (
	Neturl                                                       = "net/url"
	Time                                                         = "time"
	Constants_5                                                  = ""
	Appkeymustbeconfigured                                       = "app_key must be configured"
	BasePath                                                     = "basePath"
	Constants_12                                                 = "*"
	Context                                                      = "context"
	Math                                                         = "math"
	ApiKeyAuth                                                   = "apiKeyAuth"
	AppKeyAuth                                                   = "appKeyAuth"
	Constants_6                                                  = ""
	Accountinformationnotfound                                   = "account information not found"
	Testing                                                      = "testing"
	Fmt                                                          = "fmt"
	Constants_3                                                  = ""
	Apikeymustbeconfigured                                       = "api_key must be configured"
	DDCLIENTAPIKEY                                               = "DD_CLIENT_API_KEY"
	Httpsapidatadoghqcom                                         = "https://api.datadoghq.com/"
	Constants_4                                                  = ""
	Constants_7                                                  = ""
	Protocol                                                     = "protocol"
	V                                                            = "v2"
	SELEFRADATABASEDSN                                           = "SELEFRA_DATABASE_DSN"
	Errors                                                       = "errors"
	Os                                                           = "os"
	Constants_1                                                  = ""
	Name                                                         = "name"
	Hostuserpostgrespasswordpassportdbnamepostgressslmodedisable = "host=127.0.0.1 user=postgres password=pass port=5432 dbname=postgres sslmode=disable"
	Bytes                                                        = "bytes"
	Constants_2                                                  = ""
	Constants_8                                                  = ""
	Constants_9                                                  = "/"
	Analysisconfigerrs                                           = "analysis config err: %s"
	Constants_11                                                 = "."
	Initprovidererrors                                           = "init provider error: %s"
	Strings                                                      = "strings"
	XRatelimitReset                                              = "X-Ratelimit-Reset"
	Constants_0                                                  = ""
	RetryAfter                                                   = "Retry-After"
	Newclientserrs                                               = "new clients err: %s"
	NA                                                           = "N/A"
	Nethttp                                                      = "net/http"
	Strconv                                                      = "strconv"
	DDCLIENTAPPKEY                                               = "DD_CLIENT_APP_KEY"
	Datadog                                                      = "datadog"
	Constants_10                                                 = ""
	Notsupported                                                 = "not_supported"
	Providerpulltableerrors                                      = "provider pull table error: %s"
	Io                                                           = "io"
)
